active_modules: [pygments, tags, blog, disqus]
author: Bruno Adele
canonical_url: http://blog.jesuislibre.org/
feed:
  name: Famille de geeks
  subtitle: Une famille complètement geek
modules:
  pygments:
    style: tango
  disqus:
    shortname: blogdejesuislibreorg
